/**
 * Client-side image watermarking utility.
 * Draws a "Generated by Developer's Ai" footer with a DA logo badge
 * at the bottom of the image using HTML5 Canvas.
 *
 * The watermark is baked into the image data URL, so it persists
 * when the user downloads the image.
 */

/**
 * Apply a watermark to an image data URL.
 * @param imageDataUrl — the original base64 data URL
 * @returns — a new base64 data URL with the watermark applied
 */
export function watermarkImage(imageDataUrl: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";

    img.onload = () => {
      try {
        const originalWidth = img.naturalWidth;
        const originalHeight = img.naturalHeight;

        // Footer bar height — proportional to image size, min 60px, max 120px
        const footerHeight = Math.max(
          60,
          Math.min(120, Math.round(originalWidth * 0.08))
        );

        const canvas = document.createElement("canvas");
        canvas.width = originalWidth;
        canvas.height = originalHeight + footerHeight;
        const ctx = canvas.getContext("2d");
        if (!ctx) {
          resolve(imageDataUrl); // fallback to original
          return;
        }

        // 1. Draw the original image at the top
        ctx.drawImage(img, 0, 0, originalWidth, originalHeight);

        // 2. Draw the footer bar — deep ruby gradient
        const gradient = ctx.createLinearGradient(0, originalHeight, 0, canvas.height);
        gradient.addColorStop(0, "#1a0a0a");
        gradient.addColorStop(1, "#0d0505");
        ctx.fillStyle = gradient;
        ctx.fillRect(0, originalHeight, canvas.width, footerHeight);

        // 3. Draw a thin gold accent line at the top of the footer
        ctx.fillStyle = "#c41e3a";
        ctx.fillRect(0, originalHeight, canvas.width, 2);

        // 4. Draw the DA logo badge — a rounded square with "DA" text
        const logoSize = Math.round(footerHeight * 0.6);
        const logoX = Math.round(footerHeight * 0.25);
        const logoY = originalHeight + Math.round((footerHeight - logoSize) / 2);
        const logoRadius = Math.round(logoSize * 0.2);

        // Logo background — ruby gradient
        const logoGradient = ctx.createLinearGradient(logoX, logoY, logoX + logoSize, logoY + logoSize);
        logoGradient.addColorStop(0, "#e0245e");
        logoGradient.addColorStop(0.5, "#c41e3a");
        logoGradient.addColorStop(1, "#9b1c2e");
        ctx.fillStyle = logoGradient;
        roundRect(ctx, logoX, logoY, logoSize, logoSize, logoRadius);
        ctx.fill();

        // Logo text "DA"
        ctx.fillStyle = "#ffffff";
        ctx.font = `bold ${Math.round(logoSize * 0.45)}px sans-serif`;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText("DA", logoX + logoSize / 2, logoY + logoSize / 2 + 1);

        // 5. Draw "Generated by Developer's Ai" text
        const textX = logoX + logoSize + Math.round(footerHeight * 0.25);
        const textY = originalHeight + footerHeight / 2;

        ctx.fillStyle = "#f0f0f0";
        ctx.font = `${Math.round(footerHeight * 0.28)}px sans-serif`;
        ctx.textAlign = "left";
        ctx.textBaseline = "middle";
        ctx.fillText("Generated by", textX, textY - Math.round(footerHeight * 0.16));

        ctx.fillStyle = "#e0245e";
        ctx.font = `bold ${Math.round(footerHeight * 0.32)}px sans-serif`;
        ctx.fillText("Developer's Ai", textX, textY + Math.round(footerHeight * 0.18));

        // 6. Convert canvas back to data URL
        const watermarked = canvas.toDataURL("image/png");
        resolve(watermarked);
      } catch (err) {
        console.error("[watermark] error:", err);
        resolve(imageDataUrl); // fallback to original on error
      }
    };

    img.onerror = () => {
      resolve(imageDataUrl); // fallback to original
    };

    img.src = imageDataUrl;
  });
}

/** Helper: draw a rounded rectangle path */
function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number
) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + width, y, x + width, y + height, radius);
  ctx.arcTo(x + width, y + height, x, y + height, radius);
  ctx.arcTo(x, y + height, x, y, radius);
  ctx.arcTo(x, y, x + width, y, radius);
  ctx.closePath();
}
