/**
 * Client-side image watermarking utility.
 * Draws a footer with the actual Developer's Ai logo (custom-logo.png)
 * at the bottom of the image using HTML5 Canvas.
 *
 * The watermark is baked into the image data URL, so it persists
 * when the user downloads the image.
 *
 * Uses the emerald/teal theme (matching the app's new design).
 */

// Cache the logo image so we don't reload it every time
let cachedLogo: HTMLImageElement | null = null;

function loadLogo(): Promise<HTMLImageElement> {
  if (cachedLogo && cachedLogo.complete) {
    return Promise.resolve(cachedLogo);
  }
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      cachedLogo = img;
      resolve(img);
    };
    img.onerror = () => {
      // Fallback: if logo fails to load, resolve with null
      resolve(null as any);
    };
    img.src = "/custom-logo.png";
  });
}

export async function watermarkImage(imageDataUrl: string): Promise<string> {
  const [sourceImg, logoImg] = await Promise.all([
    loadImage(imageDataUrl),
    loadLogo(),
  ]);

  if (!sourceImg) {
    return imageDataUrl;
  }

  try {
    const originalWidth = sourceImg.naturalWidth;
    const originalHeight = sourceImg.naturalHeight;

    const footerHeight = Math.max(
      60,
      Math.min(120, Math.round(originalWidth * 0.08))
    );

    const canvas = document.createElement("canvas");
    canvas.width = originalWidth;
    canvas.height = originalHeight + footerHeight;
    const ctx = canvas.getContext("2d");
    if (!ctx) {
      return imageDataUrl;
    }

    ctx.drawImage(sourceImg, 0, 0, originalWidth, originalHeight);

    const gradient = ctx.createLinearGradient(0, originalHeight, 0, canvas.height);
    gradient.addColorStop(0, "#0a1a14");
    gradient.addColorStop(1, "#050d0a");
    ctx.fillStyle = gradient;
    ctx.fillRect(0, originalHeight, canvas.width, footerHeight);

    ctx.fillStyle = "#10b981";
    ctx.fillRect(0, originalHeight, canvas.width, 2);

    const logoSize = Math.round(footerHeight * 0.65);
    const logoX = Math.round(footerHeight * 0.25);
    const logoY = originalHeight + Math.round((footerHeight - logoSize) / 2);
    const logoRadius = Math.round(logoSize * 0.2);

    if (logoImg) {
      ctx.save();
      roundRect(ctx, logoX, logoY, logoSize, logoSize, logoRadius);
      ctx.clip();
      ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize);
      ctx.restore();

      ctx.strokeStyle = "rgba(16, 185, 129, 0.4)";
      ctx.lineWidth = 1;
      roundRect(ctx, logoX, logoY, logoSize, logoSize, logoRadius);
      ctx.stroke();
    } else {
      const logoGradient = ctx.createLinearGradient(logoX, logoY, logoX + logoSize, logoY + logoSize);
      logoGradient.addColorStop(0, "#10b981");
      logoGradient.addColorStop(1, "#0d9488");
      ctx.fillStyle = logoGradient;
      ctx.beginPath();
      ctx.arc(logoX + logoSize / 2, logoY + logoSize / 2, logoSize / 2, 0, Math.PI * 2);
      ctx.fill();
    }

    const textX = logoX + logoSize + Math.round(footerHeight * 0.25);
    const textY = originalHeight + footerHeight / 2;

    ctx.fillStyle = "#a7f3d0";
    ctx.font = `${Math.round(footerHeight * 0.26)}px sans-serif`;
    ctx.textAlign = "left";
    ctx.textBaseline = "middle";
    ctx.fillText("Generated by", textX, textY - Math.round(footerHeight * 0.16));

    ctx.fillStyle = "#10b981";
    ctx.font = `bold ${Math.round(footerHeight * 0.32)}px sans-serif`;
    ctx.fillText("Developer's Ai", textX, textY + Math.round(footerHeight * 0.18));

    return canvas.toDataURL("image/png");
  } catch (err) {
    console.error("[watermark] error:", err);
    return imageDataUrl;
  }
}

function loadImage(src: string): Promise<HTMLImageElement | null> {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = src;
  });
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number
) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + width, y, x + width, y + height, radius);
  ctx.arcTo(x + width, y + height, x, y + height, radius);
  ctx.arcTo(x, y + height, x, y, radius);
  ctx.arcTo(x, y, x + width, y, radius);
  ctx.closePath();
}
