export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-background text-foreground">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold tracking-tight">Terms and Conditions</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: September 10, 2026</p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-muted-foreground">

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Developer&apos;s Ai, available at{" "}
              <a href="https://developer-space-ai.vercel.app" target="_blank" rel="noopener noreferrer" className="underline underline-offset-2 text-foreground hover:text-foreground">
                developer-space-ai.vercel.app
              </a>{" "}
              (&quot;the Service&quot;), you agree to be bound by these Terms and Conditions. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">2. Description of Service</h2>
            <p>
              Developer&apos;s Ai is an AI-powered chatbot that provides conversational responses, code assistance, and AI-generated images. The Service is provided &quot;as is&quot; and may be modified, updated, or discontinued at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">3. Eligibility</h2>
            <p>
              You must be at least 13 years old to use the Service. By using the Service, you represent that you meet this age requirement and have the legal capacity to enter into these Terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">4. Account Registration</h2>
            <p>
              You may be required to create an account to access certain features. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You agree to provide accurate and complete information during registration.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="mt-2 list-inside list-disc space-y-1">
              <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Generate, store, or share content that is harmful, abusive, hateful, sexually explicit, or promotes violence.</li>
              <li>Attempt to reverse-engineer, decompile, or extract the underlying AI models or algorithms.</li>
              <li>Use automated tools (bots, scrapers) to access or interact with the Service without permission.</li>
              <li>Interfere with, disrupt, or overload the Service&apos;s infrastructure.</li>
              <li>Impersonate any person or entity, or misrepresent your affiliation with any person or entity.</li>
              <li>Use the Service to generate content that infringes on intellectual property rights of others.</li>
              <li>Redistribute, resell, or commercially exploit AI-generated content from the Service without permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">6. User Content</h2>
            <p>
              You retain ownership of any content you submit to the Service (prompts, messages, images). By submitting content, you grant Developer&apos;s Ai a non-exclusive, worldwide, royalty-free license to use, process, and display your content solely for the purpose of operating and improving the Service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">7. AI-Generated Content</h2>
            <p>
              All content generated by the Service (text, code, images) is provided for informational purposes only. AI-generated content may contain inaccuracies, errors, or biases. You should independently verify any critical information before relying on it. Developer&apos;s Ai makes no warranties about the accuracy, reliability, or completeness of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">8. Intellectual Property</h2>
            <p>
              The Service, including its design, code, branding, and documentation, is owned by Developer&apos;s Ai and protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of the Service without prior written consent.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">9. Privacy</h2>
            <p>
              Your use of the Service is also governed by our{" "}
              <a href="/privacy" className="underline underline-offset-2 text-foreground hover:text-foreground">
                Privacy Policy
              </a>
              , which describes how we collect, use, and protect your personal information. By using the Service, you consent to the practices described in the Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Developer&apos;s Ai shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service. The Service is provided without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">11. Service Availability</h2>
            <p>
              We do not guarantee uninterrupted or error-free operation of the Service. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We reserve the right to modify, suspend, or discontinue the Service at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">12. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">13. Third-Party Services</h2>
            <p>
              The Service may use third-party AI models and APIs. Your use of such third-party services is subject to their respective terms and policies. Developer&apos;s Ai is not responsible for the availability, accuracy, or practices of third-party services.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">14. Modifications to Terms</h2>
            <p>
              We may update these Terms from time to time. Changes will be posted on this page with an updated &quot;Last updated&quot; date. Your continued use of the Service after any changes constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">15. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of South Africa, without regard to its conflict of law principles. Any disputes arising under these Terms shall be resolved in the courts of South Africa.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">16. Contact</h2>
            <p>
              If you have questions about these Terms,{" "}
              <a href="https://musab-007.netlify.app" target="_blank" rel="noopener noreferrer" className="underline underline-offset-2 text-muted-foreground/50 hover:text-foreground transition-colors">
                click here
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-12 border-t border-border pt-6 text-center text-xs text-muted-foreground">
          <p>&copy; {new Date().getFullYear()} Developer&apos;s Ai. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
